pdfs/urls.py
from django.urls import path
from . import views

app_name = 'pdfs'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('result/', views.ResultView.as_view(), name="result"),
]

pdfsummary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pdfs.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

pdfs/models.py
from django.db import models

# Create your models here.

pdfs/forms.py
from django import forms
from django.core.mail import EmailMessage

class ContactForm(forms.Form):
    name = forms.CharField(label='Name/お名前', max_length=30)
    email = forms.EmailField(label='MailAddress/メールアドレス')
    title = forms.CharField(label='Title/件名', max_length=40)
    message = forms.CharField(label='Message/内容', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'Please enter your name. / お名前を入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'Please enter your email address. / メールアドレスを入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'Please enter the subject. / 件名を入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'Please enter the content. / 内容を入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ: {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = '***'
        to_list = [
            email
        ]
        cc_list = [
            
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class UploadImageForm(forms.Form):
    Uploadfile = forms.FileField()

pdfs/views.py
from django.shortcuts import render
from django.views import generic
from .forms import ContactForm
from .forms import UploadImageForm
from django.contrib import messages
from django.urls import reverse_lazy
import logging
from django.shortcuts import render
from .application import pdf2summary_2, pdf2summary_1
from django.conf import settings
import os


logger = logging.getLogger(__name__)

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "index.html"

    def post(self, request, *args, **kwargs):
        if 'pdf' in request.FILES:
            if "1_dan" == request.POST.get("dan"):
                form = UploadImageForm(request.POST, request.FILES)
                updata = request.FILES['pdf']    #2
                number = request.POST.get("number")
                pdf_link = request.FILES['pdf'].name
                with open(settings.MEDIA_ROOT  + '/pdf/' + request.FILES['pdf'].name, 'wb+') as f:    #3
                    for chunk in updata.chunks():
                        f.write(chunk)
                form = UploadImageForm()
                summary = pdf2summary_1.pdf_s(pdf_link, number)
                os.remove(settings.MEDIA_ROOT  + '/pdf/' + request.FILES['pdf'].name)
                context = {'form': form,
                           'summary': summary,
                           'number': number,
                           'pdf_link': pdf_link,
                           'dan': request.POST.get("dan"),
                           'type': request.POST.get("type"),
                           'lang': request.POST.get("lang"),
                           }
                return render(request, ResultView.template_name, context=context)
            else:
                form = UploadImageForm(request.POST, request.FILES)
                updata = request.FILES['pdf']    #2
                number = request.POST.get("number")
                pdf_link = request.FILES['pdf'].name
                with open(settings.MEDIA_ROOT  + '/pdf/' + request.FILES['pdf'].name, 'wb+') as f:    #3
                    for chunk in updata.chunks():
                        f.write(chunk)
                form = UploadImageForm()
                summary, text_link = pdf2summary_2.main(pdf_link, number)
                os.remove(text_link)
                os.remove(settings.MEDIA_ROOT  + '/pdf/' + request.FILES['pdf'].name)
                context = {'form': form,
                           'summary': summary,
                           'number': number,
                           'pdf_link': pdf_link,
                           'dan': request.POST.get("dan"),
                           'type': request.POST.get("type"),
                           'lang': request.POST.get("lang"),
                           }
                return render(request, ResultView.template_name, context=context)
        else:
            return render(request, self.template_name, context=self.kwargs)
        

class ContactView(generic.FormView):
    template_name = "contact.html"
    form_class = ContactForm
    success_url = reverse_lazy('pdfs:contact')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Contact sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

class ResultView(generic.TemplateView):
    template_name = "result.html"

pdfs/templates/base.html
{% load static %}

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>{% block title %}{% endblock %}</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/startbootstrap-agency-gh-pages.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body id="page-top">
	<div id="wrapper">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top {% block active_nav_contact %}{% endblock %}" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pdfs:index' %}"><img src="{% static 'assets/img/logo.svg' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'pdfs:index' %}#services">Service</a></li>
                        <li class="nav-item {% block active_inquiry %}{% endblock %}"><a class="nav-link" href="{% url 'pdfs:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block header%}{% endblock %}

        {% block contents%}{% endblock %}

        <!-- Footer -->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; PDF AutoSummary 2023 </div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Discord"><i class="fa-brands fa-discord"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="contact" aria-label="Mail"><i class="fa-regular fa-envelope"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
  	</div>
  </body>

</html>

pdfs/templates/contact.html
{% extends 'base.html' %}

{% block title %}PDF Auto Summary | お問い合わせ {% endblock %}

{% block active_nav_contact %}extra-style{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h2>お問い合わせはこちらから</h2>
            <h6>Twitter・Discordは下記アイコンよりご連絡ください</h6>
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8 extra-button">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

pdfs/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}PDF Auto Summary | どんなPDFも自動要約!!{% endblock %}

{% block header%}
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Summarize any PDF as you like!</div>
        <div class="masthead-heading text-uppercase">PDF Auto Summary</div>
        <a class="btn btn-primary btn-xl text-uppercase index-button" href="#services">Use Service</a>
    </div>
</header>
{% endblock %}

{% block contents %}
<section class="page-section" id="services">
    <div class="container">
        <div class="text-center">
            <h3 class="section-heading text-uppercase">Drop PDF,Check checkboxes and start</h3>
            <h3 class="section-subheading text-muted">ファイルをドラッグアンドドロップ・要約形式を指定して開始ボタンを押してください</h3>
        </div>
        <div class="text-center">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <input class="col-sm-4 col-form-label" type="file" accept="application/pdf" name="pdf" ></br>
                    <input class="col-sm-4 col-form-label" type="number" name="number" placeholder="要約する文字数を入力" required></br>
                    <div>
                        <input type="radio" name="dan" class="radio" value="1_dan" checked>1段組み
                        <input type="radio" name="dan" class="radio" value="2_dan">2段組み
                    </div>
                    <div>
                        <input type="radio" name="type" class="radio" value="all" checked>全体要約
                        <input type="radio" name="type" class="radio" value="order">各章要約
                        <input type="radio" name="type" class="radio" value="only_0">概要要約
                    </div>
                    <div>
                        <input type="radio" name="lang" class="radio" value="JP" checked>日本語
                        <input type="radio" name="lang" class="radio" value="EN">英語
                        <input type="radio" name="lang" class="radio" value="CN">中国語
                    </div>
                    </br>
                    <input class="btn btn-primary" type="submit" name="submit" value="開始">
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

pdfs/templates/result.html
{% extends 'base.html' %}

{% block title %}PDF Auto Summary | 要約結果 {% endblock %}

{% block active_nav_contact %}extra-style{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <h2>{{ pdf_link }}の要約結果</h2>
            <h6>PDF段組み設定： {{ dan }}</h6>
            <h6>PDF段組み設定： {{ type }}</h6>
            <h6>出力言語設定： {{ lang }}</h6>
            <h5>{{ summary }}</h5>
            <h6>要約文字数： {{ number }}</h6>

            <h2>{{ pdf_link }}に付属している図・表一覧</h2>
        </div>
    </div>
</div>
{% endblock %}